# Training Hyperparameters
training:
  weights: yolo26n.pt
  epochs: 4
  batch_size: 16
  learning_rate: 0.001
  optimizer: auto
  seed: 42
  img_size: 640      
  augmentation: true
  patience: 25         

# Data Configuration
data:

  num_classes: 10
  classes:
    - Hardhat
    - Mask
    - NO-Hardhat
    - NO-Mask
    - NO-Safety Vest
    - Person
    - Safety Cone
    - Safety Vest
    - machinery
    - vehicle

